language: node_js
node_js: 
  - "8"

branches:
  only:
    - master

before_script:
  - yarn global add firebase-tools

script :
  - firebase deploy --token "$FIREBASE_TOKEN"
after_success:  

notifications:
  email :
    on_failure: tonmanna@gmail.com
    on_success: tonmanna@gmail.com